name: Daily Qwerty Weather Bot

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  TELEGRAM_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
  TELEGRAM_CHANNEL_ID: ${{secrets.TELEGRAM_CHANNEL_ID}}
jobs:
  Daily-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: pip3 install -r requirements.txt

      - name: Run App
        run: python3 app.py
